## NOTEBOOK 1

LLM_Recommendation_Engine/

│
├── data/
│     items.csv
│     interactions.csv
│
├── notebooks/
│     01_Data_Generation.ipynb
│     02_Item_Embeddings.ipynb
│     03_User_Modeling.ipynb
│     04_FAISS_Retrieval.ipynb
│     05_Feature_Engineering.ipynb
│     06_LightGBM_Ranking.ipynb
│     07_Evaluation.ipynb
│     08_OpenAI_Explanation.ipynb
│
├── models/
│
├── app/
│
└── requirements.txt

This notebook create:
* items.csv
* interactions.csv

In [1]:
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

### Categories

In [2]:
categories = [
    "AI",
    "Machine Learning",
    "LLM",
    "Python",
    "Data Science",
    "Finance",
    "Business",
    "Cloud",
    "Deep Learning",
    "Computer Vision"
]

###  Generate Items

In [4]:
items = []

for i in range(1,1001):

    items.append([
        i,
        f"Content {i}",
        random.choice(categories)
    ])

items_df = pd.DataFrame(
    items,
    columns = [
        "item_id",
        "title",
        "category"
    ]
)

items_df.head()

   item_id      title          category
0        1  Content 1      Data Science
1        2  Content 2                AI
2        3  Content 3     Deep Learning
3        4  Content 4  Machine Learning
4        5  Content 5            Python

###  Generate Items

In [5]:
event_types = [
    "click",
    "search",
    "watch",
    "like"
]

### Generate Interactions

In [7]:
interactions = []

for _ in range(10000):
    user_id = random.randint(1,500)

    item_id = random.randint(1,1000)

    event = random.choice(event_types)

    timestamp = datetime.now() - timedelta(
        days = random.randint(0,365)
    )

    interactions.append([
        user_id,
        item_id,
        event,
        timestamp
    ])

### Convert to DataFrame

In [15]:
interactions_df = pd.DataFrame(
    interactions,
    columns = [
        "user_id",
        "item_id",
        "event_type",
        "timestamp"
    ]
)

interactions_df.head()

   user_id  item_id event_type                  timestamp
0      253      757       like 2026-06-12 21:46:26.155765
1      439      317       like 2025-07-09 21:46:26.155786
2      412      239      watch 2026-06-11 21:46:26.155794
3       42      441       like 2025-12-24 21:46:26.155801
4      230      603      click 2026-05-09 21:46:26.155807

In [16]:
items_df.to_csv("item_df.csv", index=False)
interactions_df.to_csv(
    "interactions.csv",
    index=False
)

print("CSV file saved successfully!")

CSV file saved successfully!

In [17]:
print(items_df.shape)
print(interactions_df.shape)

(1000, 3)
(10000, 4)